# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.support import expected_conditions as EC


class TestCreateEvent:
    @pytest.fixture
    def driver(self):
        driver = webdriver.Chrome()
        yield driver

    @pytest.fixture()
    def teardown(self, driver):
        driver.quit()

    def test_create_event(self, driver):
        wait = WebDriverWait(driver, timeout=10)
        driver.get("http://localhost:10080/web-apps/events-modular/index.html")
        driver.set_window_size(1200, 1200)

        time.sleep(4) # element not interactable

        # WebDriverWait(driver, 5).until(EC.element_to_be_clickable((By.ID, "navbarDropdown"))).click()
        driver.find_element(By.ID, "navbarDropdown").click()
        driver.find_element(By.LINK_TEXT, "Create Event").click()
        driver.find_element(By.NAME, "ce-description").click()
        driver.find_element(By.NAME, "ce-description").send_keys("Taylor Swing")
        driver.find_element(By.ID, "ce-active-check").click()
        driver.find_element(By.ID, "private").click()
        driver.find_element(By.NAME, "ce-date").click()
        driver.find_element(By.CSS_SELECTOR, ".datepicker-days .next").click()
        driver.find_element(
            By.CSS_SELECTOR, "tr:nth-child(4) > .day:nth-child(6)"
        ).click()
        driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        time.sleep(4) # element not interactable
        driver.find_element(By.CSS_SELECTOR, "#eventModal .btn").click()
        driver.find_element(By.ID, "navbarDropdown").click()
        driver.find_element(By.LINK_TEXT, "List Events").click()
        driver.find_element(By.CSS_SELECTOR, ".btn-sm").click()
        time.sleep(4) # element not interactable
        driver.find_element(By.ID, "confirmDeleteBtn").click()
        time.sleep(4) # element not interactable
        driver.find_element(By.LINK_TEXT, "Home").click()
        time.sleep(4)
