# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestManageevent():
  def setup_method(self, method):
    options = webdriver.ChromeOptions()
    self.driver = webdriver.Remote(command_executor='http://10.20.0.100:4444/wd/hub', options=options)
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_manageevent(self):
    self.driver.get("http://10.20.0.201/selenium/events/index.html")
    self.driver.set_window_size(1291, 855)
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "Create Event").click()
    self.driver.find_element(By.NAME, "ce-description").click()
    self.driver.find_element(By.NAME, "ce-description").send_keys("Jackson Twist")
    self.driver.find_element(By.NAME, "ce-date").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > .day:nth-child(6)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, "#eventModal .btn").click()
    self.driver.find_element(By.ID, "navbarDropdown").click()
    self.driver.find_element(By.LINK_TEXT, "List Events").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-sm").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "confirmDeleteBtn").click()
    self.driver.find_element(By.LINK_TEXT, "Home").click()
    time.sleep(30)
    self.driver.close()

