# Generated by Django 5.1.2 on 2024-11-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='prod_cat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
